/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Defines the apdex settings of an application.
type Apdex struct {

	// Apdex user satisfaction threshold (decimal number with one fractional digit).
	Threshold float32 `json:"threshold"`

	// Consider JavaScript errors in Apdex calculations
	ConsiderJavaScriptErrors bool `json:"considerJavaScriptErrors"`
}
