/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Defines how to identify an application.
type ApplicationFilter struct {

	// The string to look for.
	Pattern string `json:"pattern"`

	// Defines the matching rule.
	ApplicationMatchType string `json:"applicationMatchType"`

	// Defines where to look for the string.
	ApplicationMatchTarget string `json:"applicationMatchTarget"`
}
