/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationDataPrivacy struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// The unique id of the web application
	Identifier string `json:"identifier,omitempty"`

	// Data capture and cookies disabled until JavaScriptAPI dtrum.enable() is called enabled/disabled.
	DataCaptureOptInEnabled bool `json:"dataCaptureOptInEnabled"`

	// Set persistent cookie in order to recognize returning devices enabled/disabled.
	PersistentCookieForUserTracking bool `json:"persistentCookieForUserTracking"`

	// Browsers' \"Do Not Track\" behaviour: IGNORE_DO_NOT_TRACK/CAPTURE_ANONYMIZED/DO_NOT_CAPTURE.
	DoNotTrackBehaviour string `json:"doNotTrackBehaviour"`
}
