/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationDetectionRule struct {

	// The unique ID of the rule.    When adding a new rule, you can either specify your own ID, or don't specify anything, in that case the ID will be generated automatically.
	Uuid string `json:"uuid,omitempty"`

	// The identifier of the application, for example `APPLICATION-4A3B43`. You must use an existing ID.
	ApplicationIdentifier string `json:"applicationIdentifier"`

	// Defines how to identify an application.
	FilterConfig *ApplicationFilter `json:"filterConfig"`
}
