/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Auto tag stub - only contains id and name/key of an auto tag.
type AutoTagStub struct {

	// The id of the rule-based tag.
	Id string `json:"id,omitempty"`

	// The name/key of the rule-based tag.
	Name string `json:"name,omitempty"`
}
