/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// List of auto tag stubs
type AutoTagStubList struct {

	// Configured rule based tag stubs
	Values []AutoTagStub `json:"values,omitempty"`
}
