/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration for an auto tag. This config contains information when the tag should be automatically assigned to entities.
type AutoTag struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// The ID of the rule-based tag.
	Id string `json:"id,omitempty"`

	// The name of the rule-based tag. This is the actual tag value which is associated with entities.If a 'valueFormat' is defined inside a rule, the name of this tag will represent the tag key for this rule.
	Name string `json:"name"`

	// The list of rules when to associate this tag with an entity. Each rule is evaluated independently of all other rules.
	Rules []AutoTagRule `json:"rules,omitempty"`
}
