/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Metadata useful for debugging
type ConfigurationHistoryMetadata struct {

	// The type of configuration.
	Type_ string `json:"type,omitempty"`

	// Dynatrace server version.
	ClusterVersion string `json:"clusterVersion,omitempty"`
}
