/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConfigurationInstanceDto struct {

	// The ID of the configuration.
	Identifier string `json:"identifier,omitempty"`

	// List of all changes to the configuration.
	Revisions *interface{} `json:"revisions,omitempty"`
}
