/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Metadata useful for debugging
type ConfigurationMetadata struct {

	// Dynatrace server version.
	ClusterVersion string `json:"clusterVersion,omitempty"`

	// Sorted list containing the version numbers of the configuration.
	ConfigurationVersions []int64 `json:"configurationVersions,omitempty"`
}
