/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of lost connection detection
type ConnectionLostDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Is detection enabled during graceful host shutdowns.
	EnabledOnGracefulShutdowns bool `json:"enabledOnGracefulShutdowns"`
}
