/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Contains all settings regarding content capturing, e.g. resource timings.
type ContentCapture struct {

	// Settings for capturing resource timings.
	ResourceTimingSettings *ResourceTimingSettings `json:"resourceTimingSettings"`

	// Monitor JavaScript errors enabled/disabled.
	JavaScriptErrors bool `json:"javaScriptErrors"`

	// Detect actions that trigger setTimout XHRs enabled/disabled.
	TimedActionSupport bool `json:"timedActionSupport"`

	// Support for Visually complete and Speed index enabled/disabled.
	VisuallyCompleteAndSpeedIndex bool `json:"visuallyCompleteAndSpeedIndex"`
}
