/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomProcessMetadataKey struct {

	// Source of the custom metadata.
	Source string `json:"source"`

	// Actual key of the custom metadata.
	Key string `json:"key"`
}
