/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DataPrivacy struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// Mask IP addresses and GPS coordinates enabled/disabled.
	MaskIpAddressesAndGpsCoordinates bool `json:"maskIpAddressesAndGpsCoordinates"`

	// Mask user action names (Web applications only) enabled/disabled.
	MaskUserActionNames bool `json:"maskUserActionNames"`

	// Mask personal data in URIs enabled/disabled.
	MaskPersonalDataInUris bool `json:"maskPersonalDataInUris"`
}
