/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DiskNameFilterDto struct {

	// Comparison operator.
	Operator string `json:"operator"`

	// Value to match.
	Value string `json:"value"`
}
