/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DiskEventAnomalyDetectionConfigStub struct {

	// The ID of the disk event.
	Id string `json:"id,omitempty"`

	// The name of the disk event.
	Name string `json:"name,omitempty"`
}
