/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of low disk inodes number detection
type DiskLowInodesDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for low disk inodes number detection. If not present (null) then default thresholds will be used.
	CustomThresholds *DiskLowInodesThresholds `json:"customThresholds,omitempty"`
}
