/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for low disk inodes number detection. If not present (null) then default thresholds will be used.
type DiskLowInodesThresholds struct {

	// Detect low disk inodes when if percent of available inodes is lower than N percent in 3 out of 5 samples.
	FreeInodesPercentage int32 `json:"freeInodesPercentage"`
}
