/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of high number of backend connection errors detection on ELB
type ElbHighConnectionErrorsDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for high number of backend connection errors detection on ELB. If not present (null) then default thresholds will be used.
	CustomThresholds *ElbHighConnectionErrorsThresholds `json:"customThresholds,omitempty"`
}
