/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntityRuleEngineDynamicPgIdCalcInputConditionKey struct {

	// Defines the attribute used for the filter. Only some are allowed based on the feature it is used for and the specified 'type' outside this condition.
	Attribute string `json:"attribute"`

	Type_ string `json:"type,omitempty"`

	// Holds the attribute key of the specified 'attribute'. This must be set for attributes which need dynamic keys and must not be set for attributes which don't need dynamic keys (where the attribute itself suffices as key).
	DynamicKey string `json:"dynamicKey"`
}
