/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of high memory saturation detection on ESXi host
type EsxiHighMemoryDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for high memory saturation detection on ESXi host. If not present (null) then default thresholds will be used.
	CustomThresholds *EsxiHighMemoryThresholds `json:"customThresholds,omitempty"`
}
