/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// In addition to the event handlers, events called using addEventListener or attachEvent can be captured. Be careful with this option! Event wrappers can conflict with the JavaScript code on a web page.
type EventWrapperSettings struct {

	// Click enabled/disabled.
	Click bool `json:"click"`

	// MouseUp enabled/disabled.
	MouseUp bool `json:"mouseUp"`

	// Change enabled/disabled.
	Change bool `json:"change"`

	// Blur enabled/disabled.
	Blur bool `json:"blur"`

	// TouchStart enabled/disabled.
	TouchStart bool `json:"touchStart"`

	// TouchEnd enabled/disabled.
	TouchEnd bool `json:"touchEnd"`
}
