/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExtractSubstring struct {

	// The position of the extracted string relative to delimiters.
	Position string `json:"position"`

	// The delimiter string.
	Delimiter string `json:"delimiter"`

	// The end-delimiter string.    Required if the **position** value is `BETWEEN`. Otherwise not allowed.
	EndDelimiter string `json:"endDelimiter,omitempty"`
}
