/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Failure rate increase detection configuration.
type FailureRateIncreaseDetectionConfig struct {

	// How to detect failure rate increase: automatically, based on fixed thresholds, or do not detect.
	DetectionMode string `json:"detectionMode"`

	// Parameters of the automatic failure rate increase detection.
	AutomaticDetection *FailureRateIncreaseAutodetectionConfig `json:"automaticDetection,omitempty"`

	// Fixed thresholds for failure rate increase detection.
	Thresholds *FailureRateIncreaseThresholdConfig `json:"thresholds,omitempty"`
}
