/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for high network utilization detection. If not present (null) then default thresholds will be used.
type HighNetworkThresholds struct {

	// Detect high network utilization when receive/transmit traffic utilization is higher than N percent in 3 out of 5 samples.
	UtilizationPercentage int32 `json:"utilizationPercentage"`
}
