/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for high GC activity detection. If not present (null) then default thresholds will be used.
type HighGcActivityThresholds struct {

	// Detect high Garbage Collector activity always when GC time is higher than N percent.
	GcTimePercentage int32 `json:"gcTimePercentage"`

	// Detect high Garbage Collector activity always when GC suspension is higher than N percent in 3 out of 5 samples.
	GcSuspensionPercentage int32 `json:"gcSuspensionPercentage"`
}
