/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of high error rate detection on Lambda service
type LambdaHighErrorRateDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for high error rate detection on Lambda service. If not present (null) then default thresholds will be used.
	CustomThresholds *LambdaHighErrorRateThresholds `json:"customThresholds,omitempty"`
}
