/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for low datastore free space detection. If not present (null) then default thresholds will be used.
type LowDatastoreSpaceThresholds struct {

	// Detect low free space when it's lower than N percent.
	FreeSpacePercentage int32 `json:"freeSpacePercentage"`
}
