/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MethodReference struct {

	// The technology of the method to capture.
	Technology string `json:"technology"`

	// The visibility of the method to capture.
	Visibility string `json:"visibility"`

	// The modifiers of the method to capture.
	Modifiers []string `json:"modifiers"`

	// The class name where the method to capture resides.    Either this or the **fileName** must be set.
	ClassName string `json:"className,omitempty"`

	// The file name where the method to capture resides.    Either this or **className** must be set.
	FileName string `json:"fileName,omitempty"`

	// The name of the method to capture.
	MethodName string `json:"methodName"`

	// The list of argument types.
	ArgumentTypes []string `json:"argumentTypes"`

	// The return type.
	ReturnType string `json:"returnType"`
}
