/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Settings for real user monitoring.
type MonitoringSettings struct {

	// Capture fetch() request enabled/disabled
	FetchRequests bool `json:"fetchRequests"`

	// Support for XmlHttpRequest enabled/disabled
	XmlHttpRequest bool `json:"xmlHttpRequest"`

	// JavaScript framework support.
	JavaScriptFrameworkSupport *JavaScriptFrameworkSupport `json:"javaScriptFrameworkSupport"`

	// Contains all settings regarding content capturing, e.g. resource timings.
	ContentCapture *ContentCapture `json:"contentCapture"`

	// A regular expression to match all URLs that should be excluded from becoming XHR actions.  An empty value disables the feature.
	ExcludeXhrRegex string `json:"excludeXhrRegex"`

	// JavaScript injection mode.
	InjectionMode string `json:"injectionMode"`

	// The source path for placement of your application’s custom JavaScript library file.  An empty value sets it to the root directory of your web server.
	LibraryFileLocation string `json:"libraryFileLocation"`

	// The path where the JavaScript tag should send monitoring data.  Specify either a relative or an absolute URL. If you enter an absolute URL, data will be sent using CORS.
	MonitoringDataPath string `json:"monitoringDataPath"`

	// Additional JavaScript tag properties that are specific to your application. To do this, type key-value pairs defined using (=) and separated using a (|) symbol.
	CustomConfigurationProperties string `json:"customConfigurationProperties"`

	// Path that is to be used to identify the server’s request ID.
	ServerRequestPathId string `json:"serverRequestPathId"`

	// Use the secure cookie attribute for cookies set by Dynatrace enabled/disabled.
	SecureCookieAttribute bool `json:"secureCookieAttribute"`

	// Domain to be used for cookie placement.
	CookiePlacementDomain string `json:"cookiePlacementDomain"`

	// Optimize the value of cache control headers for use with Dynatrace real user monitoring enabled/disabled.
	CacheControlHeaderOptimizations bool `json:"cacheControlHeaderOptimizations"`

	// Advanced JavaScript tag settings.
	AdvancedJavaScriptTagSettings *AdvancedJavaScriptTagSettings `json:"advancedJavaScriptTagSettings"`
}
