/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for dropped packets detection. If not present (null) then default thresholds will be used.
type NetworkDroppedPacketsThresholds struct {

	// Detect high dropped packets number only when receive/transmit dropped packet percentage is higher than N percent in 3 out of 5 samples.
	DroppedPacketsPercentage int32 `json:"droppedPacketsPercentage"`

	// Detect high dropped packets number only when receive/transmit total packets rate is higher than N packets/s in 3 out of 5 samples.
	TotalPacketsRate int32 `json:"totalPacketsRate"`
}
