/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for TCP connection problems detection. If not present (null) then default thresholds will be used.
type NetworkTcpProblemsThresholds struct {

	// Detect TCP connection problems only when percentage of new connection failures is higher than N percent.
	NewConnectionFailuresPercentage int32 `json:"newConnectionFailuresPercentage"`

	// Detect TCP connection problems only when number of failed connections is higher than N connections/min in 3 out of 5 samples.
	FailedConnectionsNumberPerMinute int32 `json:"failedConnectionsNumberPerMinute"`
}
