/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for high retransmission rate detection. If not present (null) then default thresholds will be used.
type NetworkHighRetransmissionThresholds struct {

	// Detect high retransmission only when retransmission rate is higher than N percent.
	RetransmissionRatePercentage int32 `json:"retransmissionRatePercentage"`

	// Detect high retransmission only when number of retransmitted packets is higher than N packets/min in 3 out of 5 samples.
	RetransmittedPacketsNumberPerMinute int32 `json:"retransmittedPacketsNumberPerMinute"`
}
