/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for Java out-of-memory detection. If not present (null) then default thresholds will be used.
type OutOfMemoryThresholds struct {

	// Detect Java out of memory when number of out-of-memory exceptions per minute is N or more.
	OutOfMemoryExceptionsNumber int32 `json:"outOfMemoryExceptionsNumber"`
}
