/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of Java out-of-threads problems detection
type OutOfThreadsDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for Java out-of-threads detection. If not present (null) then default thresholds will be used.
	CustomThresholds *OutOfThreadsThresholds `json:"customThresholds,omitempty"`
}
