/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of overloaded storage detection on physical storage device
type OverloadedStorageDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for overloaded storage detection on physical storage device. If not present (null) then default thresholds will be used.
	CustomThresholds *OverloadedStorageThresholds `json:"customThresholds,omitempty"`
}
