/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of high write and/or read latency detection on RDS
type RdsHighWriteReadLatencyDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for high write and/or read latency detection on RDS. If not present (null) then default thresholds will be used.
	CustomThresholds *RdsHighLatencyThresholds `json:"customThresholds,omitempty"`
}
