/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for high memory usage detection on RDS. If not present (null) then default thresholds will be used.
type RdsHighMemoryThresholds struct {

	// Detect high memory usage only when free memory is lower than N Megabytes in 3 out of 5 samples.
	FreeMemory float32 `json:"freeMemory"`

	// Detect high memory usage only when swap usage is higher than N Gigabytes in 3 out of 5 samples.
	SwapUsage float32 `json:"swapUsage"`
}
