/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RequestAttribute struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// The ID of the request attribute.
	Id string `json:"id,omitempty"`

	// The name of the request attribute.
	Name string `json:"name"`

	// Request attribute enabled/disabled.
	Enabled bool `json:"enabled"`

	// The data type of the request attribute.
	DataType string `json:"dataType"`

	// The list of data sources.
	DataSources []DataSource `json:"dataSources"`

	// String values transformation.    If the **dataType** is not `string`, set the `Original` here.
	Normalization string `json:"normalization"`

	// Aggregation type for the request values.
	Aggregation string `json:"aggregation"`

	// Confidential data flag. Set `true` to treat the captured data as confidential.
	Confidential bool `json:"confidential"`

	// Personal data masking flag. Set `true` to skip masking. Warning: This will potentially access personalized data.
	SkipPersonalDataMasking bool `json:"skipPersonalDataMasking"`
}
