/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Response time degradation detection configuration.
type ResponseTimeDegradationDetectionConfig struct {

	// How to detect response time degradation: automatically, based on fixed thresholds, or do not detect.
	DetectionMode string `json:"detectionMode"`

	// Parameters of the automatic response time degradation detection.
	AutomaticDetection *ResponseTimeDegradationAutodetectionConfig `json:"automaticDetection,omitempty"`

	// Fixed thresholds for response time degradation detection.
	Thresholds *ResponseTimeDegradationThresholdConfig `json:"thresholds,omitempty"`
}
