/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServiceAnomalyDetectionConfig struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// How to detect response time degradation.
	ResponseTimeDegradation *ResponseTimeDegradationDetectionConfig `json:"responseTimeDegradation"`

	// How to detect failure rate increase.
	FailureRateIncrease *FailureRateIncreaseDetectionConfig `json:"failureRateIncrease"`
}
