/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SimpleTech struct {

	// Predefined technology, if technology is not predefined, then the verbatim type must be set
	Type_ string `json:"type,omitempty"`

	// Non-predefined technology, use for custom technologies.
	VerbatimType string `json:"verbatimType,omitempty"`
}
