/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of slow running physical storage device detection
type SlowPhysicalStorageDetectionConfig struct {

	// Is detection enabled.
	Enabled bool `json:"enabled"`

	// Custom thresholds for slow running physical storage device detection. If not present (null) then default thresholds will be used.
	CustomThresholds *SlowPhysicalStorageThresholds `json:"customThresholds,omitempty"`
}
