/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom thresholds for slow running physical storage device detection. If not present (null) then default thresholds will be used.
type SlowPhysicalStorageThresholds struct {

	// Detect slow running physical storage device always when read/write latency is higher than N milliseconds in 4 out of 5 samples.
	AvgReadWriteLatency int32 `json:"avgReadWriteLatency"`

	// Detect slow running physical storage device always when peak value for read/write latency is higher than N milliseconds in 4 out of 5 samples.
	PeakReadWriteLatency int32 `json:"peakReadWriteLatency"`
}
