/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration of anomaly detection for VMware
type VMwareAnomalyDetectionConfig struct {

	// Metadata useful for debugging.
	Metadata *ConfigurationMetadata `json:"metadata,omitempty"`

	// Configuration of high CPU saturation detection on ESXi host
	EsxiHighCpuSaturation *EsxiHighCpuSaturationConfig `json:"esxiHighCpuSaturation"`

	// Configuration of high memory saturation detection on ESXi host
	EsxiHighMemoryDetection *EsxiHighMemoryDetectionConfig `json:"esxiHighMemoryDetection"`

	// Configuration of overloaded storage detection on physical storage device
	OverloadedStorageDetection *OverloadedStorageDetectionConfig `json:"overloadedStorageDetection"`

	// Configuration of undersized storage device detection
	UndersizedStorageDetection *UndersizedStorageDetectionConfig `json:"undersizedStorageDetection"`

	// Configuration of slow running physical storage device detection
	SlowPhysicalStorageDetection *SlowPhysicalStorageDetectionConfig `json:"slowPhysicalStorageDetection"`

	// Configuration of high number of dropped packets detection
	DroppedPacketsDetection *DroppedPacketsDetectionConfig `json:"droppedPacketsDetection"`

	// Configuration of low datastore free space detection
	LowDatastoreSpaceDetection *LowDatastoreSpaceDetectionConfig `json:"lowDatastoreSpaceDetection"`
}
