/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValueCondition struct {

	// Operator comparing the extracted value to the comparison value.
	Operator string `json:"operator"`

	// Negate the comparison.
	Negate bool `json:"negate"`

	// The value to compare to.
	Value string `json:"value"`
}
