/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValueProcessing struct {

	// Preprocess by extracting a substring from the original value.
	ExtractSubstring *ExtractSubstring `json:"extractSubstring,omitempty"`

	// Split (preprocessed) string values at this separator.
	SplitAt string `json:"splitAt,omitempty"`

	// Prune Whitespaces. Defaults to false.
	Trim bool `json:"trim"`

	// Only capture values matching this condition.
	ValueCondition *ValueCondition `json:"valueCondition,omitempty"`

	// Extract value from captured data per regex.
	ValueExtractorRegex string `json:"valueExtractorRegex,omitempty"`
}
